# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190520_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pic']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profilepic',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
