# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190520_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
