# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photolikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user_id',
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
